### ISSUE TITLE
Clickatell Gateway : SENDERID does'nt works

### ISSUE THREAD

**Issue by rmarinier** [antonraharja/playSMS#456]
Dear all,
I'v set-up SENDERID* for Clickatell's gateway.
Every times senderid is fully completed when i write and send a message. Unfortunatly SENDERID does'nt appear on my phone (only +45 xxxx...).
nota: When i send from my script, SENDERID is ok on my phone.

* my SENDERID is approved by Clickatell

**Comment by antonraharja** [comment]
please check in Clickatell's report what sender ID was sent

**Comment by rmarinier** [comment]
I've check, and no SENDERID was sent ... but SENDERID is well defined in user preference (i leabe blank SENDERID in gateway config in order to use the one in user pref)

**Comment by antonraharja** [comment]
fixed in https://github.com/antonraharja/playSMS/commit/3f941cc223088b91e087e7bb0fb30e6ab9e31cb3

To set Sender ID from user you must do the following:

1. Remove the Module sender ID in the gateway settings and SMSC (Settings -> Manage gateway and SMSC -> Clickatell)

2. Remove the Default sender ID in main configuration (Settings -> Main configuration)

3. Add and approve sender ID for user (Settings -> Manage sender ID)

4. Select default sender ID from user configuration, not preferences (My account -> User configuration)

anton

**Comment by rmarinier** [comment]
That's exactly what i did: and that doesn't works!

**Comment by antonraharja** [comment]
what ? you followed the fix too ? I dont think so :)

Please read all post, fix your fn.php and then follow the rest

**Comment by rmarinier** [comment]
You're right. Thx. I'v fixed fn.php and that works now.
