### ISSUE TITLE
Bug in “credits”

### ISSUE THREAD

**Issue by wijde** [antonraharja/playSMS#580]
I witnessed another bug. Suppose the user has credits in the amount of 100 units. Suppose each SMS is 1 credit. Suppose the user used 35 SMS and left him 65 units. If you delete his credit, his balance (ideally) should be zeroed, i.e. on it the account should be 0. The bug is manifested in the fact that if you delete a user’s credit with a balance (it was initially 100) 65 in his account will remain -35 instead of 0. I ask to fix the bug. Thank you for your product.

**Comment by antonraharja** [comment]
You shouldn't delete the credit from Manage credit. Delete meant for correcting immediate invalid transaction, for example you meant to add 1000 but your put 10000.

If its operational already then its designed for admin to use Reduce credit instead.

In your case the user does have -35 because the cost of 35 SMS already spent. Instead of deleting the credit transaction, admin should reduce the credit by 65.
